name: rake-windows-inkscape-test # New temporary name

on: # Keep original triggers, or simplify if needed
  push:
    branches:
      # Trigger specifically on your test branch for now
      - test/update-inkscape-action
  pull_request: # Can keep this if you want PRs to your fork to trigger it

jobs:
  rake-windows-test: # Simplified job name
    name: Test Vectory on Windows with Custom Inkscape
    runs-on: windows-latest # Force Windows runner

    steps:
      # --- Basic Checkout and Ruby Setup ---
      - uses: actions/checkout@v4
        with:
          submodules: true # Keep this if vectory uses submodules

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Choose a representative Ruby version used by Metanorma
          # (Check metanorma docs or other workflows if unsure, e.g., 3.1, 3.2)
          ruby-version: '3.1'
          bundler-cache: true # Cache gems for speed

      # --- Setup Dependencies (Inkscape and Ghostscript) ---
      - name: Cache Chocolatey packages # Keep this step from original reusable workflow
        if: runner.os == 'Windows' # Condition is always true here, but keep for clarity
        uses: metanorma/ci/choco-cache-action@main

      - name: Setup Inkscape (Using Fork) # <<< YOUR MODIFIED ACTION
        uses: H3xano/ci/inkscape-setup-action@feat/update-inkscape-windows
        # Replace <your-github-username> with your actual username!

      - name: Setup Ghostscript # Keep this, vectory needs it
        uses: metanorma/ci/ghostscript-setup-action@main

      # --- Run the Tests ---
      - name: Run Rake tests
        run: bundle exec rake
        # Add any necessary environment variables if needed
        # env:
        #   CI: true