name: rake-windows-inkscape-test

on:
  push:
    branches:
      - test/update-inkscape-action
  pull_request:

jobs:
  rake-windows-test:
    name: Test Vectory on Windows with Custom Inkscape
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          # Use latest bundler, don't rely on cache for install
          bundler: 'latest'
          bundler-cache: false # Disable implicit bundle install

      - name: Install Bundler dependencies # Explicit install step
        run: bundle install --verbose # Add verbose for more logs if it fails

      # --- Setup Dependencies (Inkscape and Ghostscript) ---
      # Keep these commented out for now to isolate the bundler issue
      # - name: Cache Chocolatey packages
      #   if: runner.os == 'Windows'
      #   uses: metanorma/ci/choco-cache-action@main
      #
      # - name: Setup Inkscape (Using Fork)
      #   uses: <your-github-username>/ci/inkscape-setup-action@feat/update-inkscape-windows
      #
      # - name: Setup Ghostscript
      #   uses: metanorma/ci/ghostscript-setup-action@main

      # --- Run the Tests ---
      # Keep this commented out for now
      # - name: Run Rake tests
      #   run: bundle exec rake