name: rake-windows-inkscape-test

on:
  push:
    branches:
      - test/update-inkscape-action
  pull_request:

jobs:
  rake-windows-test:
    name: Test Vectory on Windows with Custom Inkscape
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler: 'latest'
          bundler-cache: false # Keep false

      # --- Add this step ---
      - name: Install MSYS2 development toolchain # Explicitly install build tools
        if: runner.os == 'Windows'
        run: ridk install 3
        # '3' selects the "MSYS2 and MINGW development toolchain" option
      # --- End of added step ---

      - name: Install Bundler dependencies
        run: bundle install --verbose # Keep verbose

      # --- Dependencies (keep commented) ---
      # - name: Cache Chocolatey packages
      #   if: runner.os == 'Windows'
      #   uses: metanorma/ci/choco-cache-action@main
      #
      # - name: Setup Inkscape (Using Fork)
      #   uses: <your-github-username>/ci/inkscape-setup-action@feat/update-inkscape-windows
      #
      # - name: Setup Ghostscript
      #   uses: metanorma/ci/ghostscript-setup-action@main

      # --- Tests (keep commented) ---
      # - name: Run Rake tests
      #   run: bundle exec rake