name: rake-windows-inkscape-test

on:
  push:
    branches:
      - test/update-inkscape-action
  pull_request:

jobs:
  rake-windows-test:
    name: Test Vectory on Windows with Custom Inkscape
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # --- Change this line ---
          ruby-version: '3.0' # Downgrade to Ruby 3.0.x
          # --- End of change ---
          bundler: 'latest'
          bundler-cache: false

      - name: Install MSYS2 development toolchain
        if: runner.os == 'Windows'
        run: ridk install 3
        # Keep this step, it might still be needed for other gems

      - name: Install Bundler dependencies
        run: bundle install --verbose

      # --- Dependencies (keep commented for now) ---
      # - name: Cache Chocolatey packages
      #   if: runner.os == 'Windows'
      #   uses: metanorma/ci/choco-cache-action@main
      #
      # - name: Setup Inkscape (Using Fork)
      #   uses: <your-github-username>/ci/inkscape-setup-action@feat/update-inkscape-windows
      #
      # - name: Setup Ghostscript
      #   uses: metanorma/ci/ghostscript-setup-action@main

      # --- Tests (keep commented for now) ---
      # - name: Run Rake tests
      #   run: bundle exec rake