name: rake-windows-inkscape-test

on:
  push:
    branches:
      - test/update-inkscape-action
  pull_request:

jobs:
  rake-windows-test:
    name: Test Vectory on Windows with Custom Inkscape
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Ruby # Revert to Ruby 3.1 and use bundler-cache
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Use a version from the main matrix
          bundler-cache: true # Mimic main repo, implicitly runs install using Gemfile.lock

      # REMOVE these steps for now:
      # - name: Install MSYS2 development toolchain
      #   if: runner.os == 'Windows'
      #   run: ridk install 3
      #
      # - name: Install Bundler dependencies
      #   run: bundle install --verbose

      # --- Dependencies (Uncomment these now!) ---
      - name: Cache Chocolatey packages
        if: runner.os == 'Windows'
        uses: metanorma/ci/choco-cache-action@main

      - name: Setup Inkscape (Using Fork) # <<< YOUR MODIFIED ACTION
        uses: H3xano/ci/inkscape-setup-action@feat/update-inkscape-windows
        # Replace <your-github-username>

      - name: Setup Ghostscript
        uses: metanorma/ci/ghostscript-setup-action@main

      # --- Tests (Uncomment this now!) ---
      - name: Run Rake tests
        run: bundle exec rake